/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk;

import com.writer.sdk.utils.HTTPClient;
import com.writer.sdk.models.shared.Security;
import java.util.Map;
import java.util.HashMap;

class SDKConfiguration {
	public HTTPClient defaultClient;
	public HTTPClient securityClient;
	public Security security;
	public String serverUrl;
	public int serverIdx = 0;
	public String language = "java";
	public String openapiDocVersion = "1.7";
	public String sdkVersion = "0.46.1";
	public String genVersion = "2.259.1";
	public String userAgent = "speakeasy-sdk/java 0.46.1 2.259.1 1.7 com.writer.sdk";
	public Map<String, Map<String, Map<String, java.lang.Object>>> globals = new HashMap<String, Map<String, Map<String, java.lang.Object>>>(){{
		put("parameters", new HashMap<String, Map<String, java.lang.Object>>());
	}};
	
}