/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk;

import com.writer.sdk.utils.HTTPClient;
import com.writer.sdk.utils.SpeakeasyHTTPClient;

public class Writer {
	/**
	 * SERVERS contains the list of server urls available to the SDK.
	 */
	public static final String[] SERVERS = {
        "https://enterprise-api.writer.com",
	};
  	
    /**
     * Methods related to AI Content Detector
     */
    public AIContentDetector aiContentDetector;
    /**
     * Methods related to Billing
     */
    public Billing billing;
    /**
     * Methods related to CoWrite
     */
    public CoWrite coWrite;
    /**
     * Methods related to Completions
     */
    public Completions completions;
    /**
     * Methods related to Content
     */
    public Content content;
    /**
     * Methods related to Download the customized model
     */
    public DownloadTheCustomizedModel downloadTheCustomizedModel;
    /**
     * Methods related to Files
     */
    public Files files;
    /**
     * Methods related to Model Customization
     */
    public ModelCustomization modelCustomization;
    /**
     * Methods related to Model
     */
    public Models models;
    /**
     * Methods related to Snippets
     */
    public Snippet snippet;
    /**
     * Methods related to Styleguide
     */
    public Styleguide styleguide;
    /**
     * Methods related to Terminology
     */
    public Terminology terminology;
    /**
     * Methods related to User
     */
    public User user;	

	private SDKConfiguration sdkConfiguration;

	/**
	 * The Builder class allows the configuration of a new instance of the SDK.
	 */
	public static class Builder {
		private SDKConfiguration sdkConfiguration = new SDKConfiguration();

		private Builder() {
		}

		/**
		 * Allows the default HTTP client to be overridden with a custom implementation.
		 * @param client The HTTP client to use for all requests.
		 * @return The builder instance.
		 */
		public Builder setClient(HTTPClient client) {
			this.sdkConfiguration.defaultClient = client;
			return this;
		}
		
		/**
		 * Configures the SDK to use the provided security details.
		 * @param security The security details to use for all requests.
		 * @return The builder instance.
		 */
		public Builder setSecurity(com.writer.sdk.models.shared.Security security) {
			this.sdkConfiguration.security = security;
			return this;
		}
		
		/**
		 * Allows the overriding of the default server URL.
		 * @param serverUrl The server URL to use for all requests.
		 * @return The builder instance.
		 */
		public Builder setServerURL(String serverUrl) {
			this.sdkConfiguration.serverUrl = serverUrl;
			return this;
		}
		
		/**
		 * Allows the overriding of the default server URL  with a templated URL populated with the provided parameters.
		 * @param serverUrl The server URL to use for all requests.
		 * @param params The parameters to use when templating the URL.
		 * @return The builder instance.
		 */
		public Builder setServerURL(String serverUrl, java.util.Map<String, String> params) {
			this.sdkConfiguration.serverUrl = com.writer.sdk.utils.Utils.templateUrl(serverUrl, params);
			return this;
		}
		
		/**
		 * Allows the overriding of the default server by index
		 * @param serverIdx The server to use for all requests.
		 * @return The builder instance.
		 */
		public Builder setServerIndex(int serverIdx) {
			this.sdkConfiguration.serverIdx = serverIdx;
			this.sdkConfiguration.serverUrl = SERVERS[serverIdx];
			return this;
		}
		
		/**
		 * Allows setting the organizationId parameter for all supported operations.
		 * @param organizationId The value to set.
		 * @return The builder instance.
		 */
		public Builder setOrganizationId(Long organizationId) {
			if (!this.sdkConfiguration.globals.get("parameters").containsKey("pathParam")) {
				this.sdkConfiguration.globals.get("parameters").put("pathParam", new java.util.HashMap<String, Object>());
			}

			this.sdkConfiguration.globals.get("parameters").get("pathParam").put("organizationId", organizationId);

			return this;
		}
		
		/**
		 * Builds a new instance of the SDK.
		 * @return The SDK instance.
		 * @throws Exception Thrown if the SDK could not be built.
		 */
		public Writer build() throws Exception {
			if (this.sdkConfiguration.defaultClient == null) {
				this.sdkConfiguration.defaultClient = new SpeakeasyHTTPClient();
			}
			
			if (this.sdkConfiguration.security != null) {
				this.sdkConfiguration.securityClient = com.writer.sdk.utils.Utils.configureSecurityClient(this.sdkConfiguration.defaultClient, this.sdkConfiguration.security);
			}
			
			if (this.sdkConfiguration.securityClient == null) {
				this.sdkConfiguration.securityClient = this.sdkConfiguration.defaultClient;
			}
			
			if (this.sdkConfiguration.serverUrl == null || this.sdkConfiguration.serverUrl.isBlank()) {
				this.sdkConfiguration.serverUrl = SERVERS[0];
				this.sdkConfiguration.serverIdx = 0;
			}

			if (this.sdkConfiguration.serverUrl.endsWith("/")) {
				this.sdkConfiguration.serverUrl = this.sdkConfiguration.serverUrl.substring(0, this.sdkConfiguration.serverUrl.length() - 1);
			}
			
			return new Writer(this.sdkConfiguration);
		}
	}

	/**
	 * Get a new instance of the SDK builder to configure a new instance of the SDK.
	 * @return The SDK builder instance.
	 */
	public static Builder builder() {
		return new Builder();
	}

	private Writer(SDKConfiguration sdkConfiguration) throws Exception {
		this.sdkConfiguration = sdkConfiguration;
		
		this.aiContentDetector = new AIContentDetector(this.sdkConfiguration);
		
		this.billing = new Billing(this.sdkConfiguration);
		
		this.coWrite = new CoWrite(this.sdkConfiguration);
		
		this.completions = new Completions(this.sdkConfiguration);
		
		this.content = new Content(this.sdkConfiguration);
		
		this.downloadTheCustomizedModel = new DownloadTheCustomizedModel(this.sdkConfiguration);
		
		this.files = new Files(this.sdkConfiguration);
		
		this.modelCustomization = new ModelCustomization(this.sdkConfiguration);
		
		this.models = new Models(this.sdkConfiguration);
		
		this.snippet = new Snippet(this.sdkConfiguration);
		
		this.styleguide = new Styleguide(this.sdkConfiguration);
		
		this.terminology = new Terminology(this.sdkConfiguration);
		
		this.user = new User(this.sdkConfiguration);
	}
}