/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;

public class CreateModelCustomizationCompletionRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.writer.sdk.models.shared.CompletionRequest completionRequest;

    public CreateModelCustomizationCompletionRequest withCompletionRequest(com.writer.sdk.models.shared.CompletionRequest completionRequest) {
        this.completionRequest = completionRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customizationId")
    public String customizationId;

    public CreateModelCustomizationCompletionRequest withCustomizationId(String customizationId) {
        this.customizationId = customizationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=modelId")
    public String modelId;

    public CreateModelCustomizationCompletionRequest withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public CreateModelCustomizationCompletionRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    public CreateModelCustomizationCompletionRequest(@JsonProperty("CompletionRequest") com.writer.sdk.models.shared.CompletionRequest completionRequest, @JsonProperty("customizationId") String customizationId, @JsonProperty("modelId") String modelId) {
        this.completionRequest = completionRequest;
        this.customizationId = customizationId;
        this.modelId = modelId;
  }
}
