/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;

public class CreateModelCustomizationRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.writer.sdk.models.shared.CreateCustomizationRequest createCustomizationRequest;

    public CreateModelCustomizationRequest withCreateCustomizationRequest(com.writer.sdk.models.shared.CreateCustomizationRequest createCustomizationRequest) {
        this.createCustomizationRequest = createCustomizationRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=modelId")
    public String modelId;

    public CreateModelCustomizationRequest withModelId(String modelId) {
        this.modelId = modelId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public CreateModelCustomizationRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    public CreateModelCustomizationRequest(@JsonProperty("CreateCustomizationRequest") com.writer.sdk.models.shared.CreateCustomizationRequest createCustomizationRequest, @JsonProperty("modelId") String modelId) {
        this.createCustomizationRequest = createCustomizationRequest;
        this.modelId = modelId;
  }
}
