/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;


public class DeleteTermsRequest {
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Request-ID")
    public String xRequestID;

    public DeleteTermsRequest withXRequestID(String xRequestID) {
        this.xRequestID = xRequestID;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=ids")
    public Long[] ids;

    public DeleteTermsRequest withIds(Long[] ids) {
        this.ids = ids;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public DeleteTermsRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    public Long teamId;

    public DeleteTermsRequest withTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }
    
    public DeleteTermsRequest(@JsonProperty("teamId") Long teamId) {
        this.teamId = teamId;
  }
}
