/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;




public class DeleteFileResponseBody {
    public DeleteFileResponseBody(){}
}
