/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;


public class DetectContentRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.writer.sdk.models.shared.ContentDetectorRequest contentDetectorRequest;

    public DetectContentRequest withContentDetectorRequest(com.writer.sdk.models.shared.ContentDetectorRequest contentDetectorRequest) {
        this.contentDetectorRequest = contentDetectorRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public DetectContentRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    public DetectContentRequest(@JsonProperty("ContentDetectorRequest") com.writer.sdk.models.shared.ContentDetectorRequest contentDetectorRequest) {
        this.contentDetectorRequest = contentDetectorRequest;
  }
}
