/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FindSnippetsSortOrderEnum
 */
public enum FindSnippetsSortOrderEnum {
    ASC("asc"),
    DESC("desc");

    @JsonValue
    public final String value;

    private FindSnippetsSortOrderEnum(String value) {
        this.value = value;
    }
}
