/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;


public class GetDocumentDetailsRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=documentId")
    public Long documentId;

    public GetDocumentDetailsRequest withDocumentId(Long documentId) {
        this.documentId = documentId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public GetDocumentDetailsRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    public Long teamId;

    public GetDocumentDetailsRequest withTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }
    
    public GetDocumentDetailsRequest(@JsonProperty("documentId") Long documentId, @JsonProperty("teamId") Long teamId) {
        this.documentId = documentId;
        this.teamId = teamId;
  }
}
