/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;

public class ListTemplatesRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;
    public ListTemplatesRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    public Long teamId;
    public ListTemplatesRequest withTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=templateId")
    public String templateId;
    public ListTemplatesRequest withTemplateId(String templateId) {
        this.templateId = templateId;
        return this;
    }
    

    public ListTemplatesRequest(@JsonProperty("teamId") Long teamId, @JsonProperty("templateId") String templateId) {
    this.teamId = teamId;
this.templateId = templateId;
  }
}
