/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;


public class ListTeamDocumentsRequest {
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=limit")
    public Integer limit;

    public ListTeamDocumentsRequest withLimit(Integer limit) {
        this.limit = limit;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=offset")
    public Long offset;

    public ListTeamDocumentsRequest withOffset(Long offset) {
        this.offset = offset;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public ListTeamDocumentsRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=search")
    public String search;

    public ListTeamDocumentsRequest withSearch(String search) {
        this.search = search;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sortField")
    public ListTeamDocumentsSortField sortField;

    public ListTeamDocumentsRequest withSortField(ListTeamDocumentsSortField sortField) {
        this.sortField = sortField;
        return this;
    }
    
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=sortOrder")
    public ListTeamDocumentsSortOrder sortOrder;

    public ListTeamDocumentsRequest withSortOrder(ListTeamDocumentsSortOrder sortOrder) {
        this.sortOrder = sortOrder;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    public Long teamId;

    public ListTeamDocumentsRequest withTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }
    
    public ListTeamDocumentsRequest(@JsonProperty("teamId") Long teamId) {
        this.teamId = teamId;
  }
}
