/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListPagesStatus
 */
public enum ListPagesStatus {
    LIVE("live"),
    OFFLINE("offline");

    @JsonValue
    public final String value;

    private ListPagesStatus(String value) {
        this.value = value;
    }
}
