/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListUsersQueryParamSortField
 */
public enum ListUsersQueryParamSortField {
    ID("id"),
    NAME("name"),
    CREATION_TIME("creationTime"),
    DELETED("deleted"),
    MODIFICATION_TIME("modificationTime"),
    EMAIL("email"),
    LAST_SEEN("lastSeen");

    @JsonValue
    public final String value;

    private ListUsersQueryParamSortField(String value) {
        this.value = value;
    }
}
