/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ListTeamDocumentsQueryParamSortField
 */
public enum ListTeamDocumentsQueryParamSortField {
    TITLE("title"),
    CREATION_TIME("creationTime"),
    MODIFICATION_TIME("modificationTime"),
    MODIFIED_BY_ME_TIME("modifiedByMeTime"),
    OPENED_BY_ME_TIME("openedByMeTime");

    @JsonValue
    public final String value;

    private ListTeamDocumentsQueryParamSortField(String value) {
        this.value = value;
    }
}
