/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.writer.sdk.utils.SpeakeasyMetadata;

public class PageDetailsRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=pageId")
    public Long pageId;
    public PageDetailsRequest withPageId(Long pageId) {
        this.pageId = pageId;
        return this;
    }
    
}
