/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SortField
 */
public enum SortField {
    SHORTCUT("shortcut"),
    CREATION_TIME("creationTime"),
    MODIFICATION_TIME("modificationTime");

    @JsonValue
    public final String value;

    private SortField(String value) {
        this.value = value;
    }
}
