/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;


public class UpdateTermsRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public com.writer.sdk.models.shared.UpdateTermsRequest updateTermsRequest;

    public UpdateTermsRequest withUpdateTermsRequest(com.writer.sdk.models.shared.UpdateTermsRequest updateTermsRequest) {
        this.updateTermsRequest = updateTermsRequest;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=X-Request-ID")
    public String xRequestID;

    public UpdateTermsRequest withXRequestID(String xRequestID) {
        this.xRequestID = xRequestID;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public UpdateTermsRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=teamId")
    public Long teamId;

    public UpdateTermsRequest withTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }
    
    public UpdateTermsRequest(@JsonProperty("UpdateTermsRequest") com.writer.sdk.models.shared.UpdateTermsRequest updateTermsRequest, @JsonProperty("teamId") Long teamId) {
        this.updateTermsRequest = updateTermsRequest;
        this.teamId = teamId;
  }
}
