/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;

public class UploadFileRequest {
    @SpeakeasyMetadata("request:mediaType=multipart/form-data")
    public com.writer.sdk.models.shared.UploadModelFileRequest uploadModelFileRequest;

    public UploadFileRequest withUploadModelFileRequest(com.writer.sdk.models.shared.UploadModelFileRequest uploadModelFileRequest) {
        this.uploadModelFileRequest = uploadModelFileRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=organizationId")
    public Long organizationId;

    public UploadFileRequest withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    public UploadFileRequest(@JsonProperty("UploadModelFileRequest") com.writer.sdk.models.shared.UploadModelFileRequest uploadModelFileRequest) {
        this.uploadModelFileRequest = uploadModelFileRequest;
  }
}
