/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.writer.sdk.utils.DateTimeDeserializer;
import com.writer.sdk.utils.DateTimeSerializer;
import java.time.OffsetDateTime;


public class BriefDocument {
    @JsonProperty("access")
    public BriefDocumentAccess access;

    public BriefDocument withAccess(BriefDocumentAccess access) {
        this.access = access;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("createdUser")
    public SimpleUser createdUser;

    public BriefDocument withCreatedUser(SimpleUser createdUser) {
        this.createdUser = createdUser;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("creationTime")
    public OffsetDateTime creationTime;

    public BriefDocument withCreationTime(OffsetDateTime creationTime) {
        this.creationTime = creationTime;
        return this;
    }
    
    @JsonProperty("id")
    public Long id;

    public BriefDocument withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("modificationTime")
    public OffsetDateTime modificationTime;

    public BriefDocument withModificationTime(OffsetDateTime modificationTime) {
        this.modificationTime = modificationTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("modifiedUser")
    public SimpleUser modifiedUser;

    public BriefDocument withModifiedUser(SimpleUser modifiedUser) {
        this.modifiedUser = modifiedUser;
        return this;
    }
    
    @JsonProperty("organizationId")
    public Long organizationId;

    public BriefDocument withOrganizationId(Long organizationId) {
        this.organizationId = organizationId;
        return this;
    }
    
    @JsonProperty("score")
    public Long score;

    public BriefDocument withScore(Long score) {
        this.score = score;
        return this;
    }
    
    @JsonProperty("teamId")
    public Long teamId;

    public BriefDocument withTeamId(Long teamId) {
        this.teamId = teamId;
        return this;
    }
    
    @JsonProperty("title")
    public String title;

    public BriefDocument withTitle(String title) {
        this.title = title;
        return this;
    }
    
    public BriefDocument(@JsonProperty("access") BriefDocumentAccess access, @JsonProperty("creationTime") OffsetDateTime creationTime, @JsonProperty("id") Long id, @JsonProperty("modificationTime") OffsetDateTime modificationTime, @JsonProperty("organizationId") Long organizationId, @JsonProperty("score") Long score, @JsonProperty("teamId") Long teamId, @JsonProperty("title") String title) {
        this.access = access;
        this.creationTime = creationTime;
        this.id = id;
        this.modificationTime = modificationTime;
        this.organizationId = organizationId;
        this.score = score;
        this.teamId = teamId;
        this.title = title;
  }
}
