/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class BriefDocuments {
    @JsonProperty("pagination")
    public Pagination pagination;

    public BriefDocuments withPagination(Pagination pagination) {
        this.pagination = pagination;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("result")
    public BriefDocument[] result;

    public BriefDocuments withResult(BriefDocument[] result) {
        this.result = result;
        return this;
    }
    
    @JsonProperty("totalCount")
    public Long totalCount;

    public BriefDocuments withTotalCount(Long totalCount) {
        this.totalCount = totalCount;
        return this;
    }
    
    public BriefDocuments(@JsonProperty("pagination") Pagination pagination, @JsonProperty("totalCount") Long totalCount) {
        this.pagination = pagination;
        this.totalCount = totalCount;
  }
}
