/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class DeleteResponse {
    @JsonProperty("deleted")
    public Long deleted;

    public DeleteResponse withDeleted(Long deleted) {
        this.deleted = deleted;
        return this;
    }
    
    public DeleteResponse(@JsonProperty("deleted") Long deleted) {
        this.deleted = deleted;
  }
}
