/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum GenerationModelInfoResponseType {
    GPT("GPT"),
    INSTRUCT("Instruct");

    @JsonValue
    public final String value;

    private GenerationModelInfoResponseType(String value) {
        this.value = value;
    }
}
