/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

public class GenerationModelsResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public GenerationModelInfoResponse[] data;

    public GenerationModelsResponse withData(GenerationModelInfoResponse[] data) {
        this.data = data;
        return this;
    }
    
    public GenerationModelsResponse(){}
}
