/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum InputType {
    TEXTBOX("textbox"),
    TEXTAREA("textarea"),
    DROPDOWN("dropdown");

    @JsonValue
    public final String value;

    private InputType(String value) {
        this.value = value;
    }
}
