/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

public enum PagePublicApiResponseStatus {
    LIVE("live"),
    OFFLINE("offline");

    @JsonValue
    public final String value;

    private PagePublicApiResponseStatus(String value) {
        this.value = value;
    }
}
