/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.writer.sdk.utils.SpeakeasyMetadata;

public class Security {
    @SpeakeasyMetadata("security:scheme=true,type=apiKey,subtype=header,name=Authorization")
    public String apiKey;
    public Security withApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }
    
}
