/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

public class TermTagResponse {
    @JsonProperty("id")
    public Long id;
    public TermTagResponse withId(Long id) {
        this.id = id;
        return this;
    }
    
    @JsonProperty("parentTagId")
    public Long parentTagId;
    public TermTagResponse withParentTagId(Long parentTagId) {
        this.parentTagId = parentTagId;
        return this;
    }
    
    @JsonProperty("tag")
    public String tag;
    public TermTagResponse withTag(String tag) {
        this.tag = tag;
        return this;
    }
    
    @JsonProperty("termId")
    public Long termId;
    public TermTagResponse withTermId(Long termId) {
        this.termId = termId;
        return this;
    }
    
    public TermTagResponse(@JsonProperty("id") Long id, @JsonProperty("parentTagId") Long parentTagId, @JsonProperty("tag") String tag, @JsonProperty("termId") Long termId) {
        this.id = id;
        this.parentTagId = parentTagId;
        this.tag = tag;
        this.termId = termId;
  }
}
