/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.writer.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.writer.sdk.utils.SpeakeasyMetadata;


public class UploadModelFileRequest {
    @SpeakeasyMetadata("multipartForm:file")
    public File file;

    public UploadModelFileRequest withFile(File file) {
        this.file = file;
        return this;
    }
    
    public UploadModelFileRequest(@JsonProperty("file") File file) {
        this.file = file;
  }
}
